services:
  server:
    image: mapit-server:latest
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=mapit
      - DATABASE_PASSWORD=mapit
      - DATABASE_DATABASE=mapit
      - DATABASE_NAME=mapit
      - DATABASE_TYPE=mysql
      - JWT_SECRET=secretxxxxx
      - CACHE_STORE=redis
      - CACHE_HOST=redis
      - CACHE_PORT=6379
    depends_on:
      - mysql
      - redis

  redis:
    image: redis

  mysql:
    image: mysql:latest
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mapit
      - MYSQL_PASSWORD=mapit
      - MYSQL_USER=mapit
      - MYSQL_ROOT_HOST=0.0.0.0
