mapit:
  admin:
    username: admin
    password: ${quarkus.uuid}
quarkus:
  http:
    enable-compression: true
    port: 19090
  console:
    color: true
  hibernate-orm:
    log:
      sql: true
  log:
    console:
      json: false
    level: INFO
  quinoa:
    build-dir: dist
    enable-spa-routing: true
  management:
    enabled: true
  live-reload:
    instrumentation: true
  package:
    jar:
      appcds:
        enabled: true
  websockets-next:
    server:
      auto-ping-interval: 1
      traffic-logging:
        enabled: true
  container-image:
    group: mapit
    name: server